### ISSUE TITLE
Playerframe -> Classbar

### ISSUE THREAD

**Issue by Floppy513** [ElvUI-WotLK/ElvUI#281]
Didn't test it on other classes than DK.
The runes are inverted in 50% of the cases I login/relog.

Infight, they are randomly shown as ready, not-ready and recharging, can't make out a scheme.
They are more or less flashing randomly when infight.

Also all of them are flashing ready when I use one.

**Comment by silentwinter** [comment]
This is not the UI's fault, but it's server's fault. It was fixed later in Cataclysm of faulty communication between client and server. 

Client thinks it is ready RIGHT after it being used although it is not on the server side. That's why you see the rune as ready, but cannot be used. 

After playing for awhile, you will get used to it.

**Comment by Floppy513** [comment]
Alright, thanks for the quick answer
