### ISSUE TITLE
Undead Nameplate 3D portrait

### ISSUE THREAD

**Issue by Animuswow** [ElvUI-WotLK/ElvUI#406]
The 3D portrait nameplate for all undead shows only the body instead of the face, while it should show the face only.
Have confirmed that i'm using the lastest updated elvui.
![untitled](https://cloud.githubusercontent.com/assets/29161062/26753031/ee4fa39e-488f-11e7-9554-9ac60719de64.jpg)

**Comment by crumdidlyumshis** [comment]
If your using WoD models it's the patch that makes has this bug not ElvUI unfortunately :(

**Comment by Animuswow** [comment]
@crumdidlyumshis hmm, i'll download the non WOD models version and give it a shot, thanks mate! :D

**Comment by crumdidlyumshis** [comment]
NP! :)

**Comment by AndehX** [comment]
Just registered to report on this issue.

I contacted the author of the WoD models on the modcraft.io forum, and he claims there is no issue with 3D portraits using the default blizzard UI.  He pointed me to this github to bring the issue up here.

**Comment by Kkthnx** [comment]
This is an issue with the models. Not the UI. If you disable the Models, it will work fine.

**Comment by crumdidlyumshis** [comment]
Yes this is a issue with the models and not ElvUI. There is a possible hack that can fix this but it's not necessary as it is the models that produce this bug. I've tested this multiple times in the past with the wod models.

**Comment by AndehX** [comment]
I've reported the issue to the WoD models author, but he seems to believe its not an issue with his models.  I'm not sure he's willing to accept its his problem.  Maybe a couple of you guys could chime in?  http://www.modcraft.io/index.php?topic=10800.270

**Comment by crumdidlyumshis** [comment]
Of course, its Finsternis. He is super difficult to communicate to and he likes to point the fault elsewhere. I've messaged him about before. All is good according to him. >_>I am not sure what else to do. I will make a post about it too I suppose.

**Comment by AndehX** [comment]
I tried the patch suggested in that thread, but it completely breaks the unitframes.

**Comment by Kkthnx** [comment]
Maybe we can release a small addon to patch this until the said guy can accept the problem he has and fix it or people can use a small addon we make to hook into and tweak this for uses.

**Comment by crumdidlyumshis** [comment]
@kkthnx that sounds like a good solution until then :)

**Comment by AndehX** [comment]
@Kkthnx what is this addon you speak of?

**Comment by silentwinter** [comment]
This has been an issue ever since Fern released his legion pack. And yes, as Crum pointed out, I opened this issue and closed it as I was able to manually fix it by doing this : https://github.com/ElvUI-WotLK/ElvUI/compare/master...silentwinter:patch-1

I've noticed an issue with the code above; you gotta add "then" at the end of line 119.

It should fix all the portrait issues. Only problem is that your character will "bump" into and look really ugly.

Perfectly fine for Dwarf female, Human females. A lil issue with Undeads only.

**Comment by silentwinter** [comment]
Basically, on ElvUI/modules/unitframes/elements/portrait.lua

On the last function, add this line of code.
`	if(self:GetObjectType() ~= "Texture") then
		local model = self:GetModel();
		if(model and model.find and model:find("dwarfmale.m2"))
		or(model and model.find and model:find("humanfemale.m2")) 
		or(model and model.find and model:find("scourgemale.m2"))
		or(model and model.find and model:find("scourgefemale.m2")) then
			self:SetCamera(1)
		end
	end`

**Comment by Loaal** [comment]
Fix added to [ElvUI_Enchanced](https://github.com/ElvUI-WotLK/ElvUI_Enhanced)

**Comment by AndehX** [comment]
Perfect!  works great, even for Undead.  Thanks!

**Comment by Aleopca** [comment]
In relation to the last comment posted that it works for undeads, it "works" in the sense it does center the portrait on the head but other than that it is unusable since the zoom just goes straight through the face.
![wowscrnshot_022419_110723](https://user-images.githubusercontent.com/47941386/53298442-3627c700-3826-11e9-9bf6-f0f6c3823066.jpg)
